# -*- coding: utf-8 -*-
"""Bosques aleatorios.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mV3040phttsKzJp9XLYRtv9LITXX54YS
"""

from sklearn import datasets
from sklearn.model_selection import train_test_split
#Bosques aleatorios
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn import metrics
from sklearn.metrics import confusion_matrix

#Importamos los datos de la misma librería de scikit-learn
dataset = datasets.load_breast_cancer()
print(dataset)

#Verificar datos
print('Información en el dataset:')
print(dataset.keys())
print()

print('Características del dataset:')
print(dataset.DESCR)

#Validar los datos
X = dataset.data
y = dataset.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Definir algoritmo a utilizar bosques aleatorios
algoritmo = RandomForestClassifier(n_estimators = 10, criterion = 'entropy')

# Entrenar y predecir el modelo
algoritmo.fit(X_train, y_train)
y_pred = algoritmo.predict(X_test)

#Verificar la matriz de Confusión
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)
#Calcular la precisión del modelo
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred)
print('Precisión del modelo:')
print(precision)